name: iotemplateapp
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - nuitka
  - pyyaml
  - tomli-w
  - virtualenv
  - pip:
    - git+https://IoAeroMachineUser:${PYPI_PAT}@github.com/io-aero/io-common.git
    - git+https://@github.com/io-aero/io-template-lib.git
    # Development dependencies
    - bandit
    - black
    - coverage
    - coveralls
    - docformatter
    - furo
    - mypy
    - myst-parser
    - ordered-set
    - pylint
    - pytest
    - pytest-cov
    - pytest-deadfixtures
    - pytest-helpers-namespace
    - pytest-random-order
    - rinohtype
    - ruff
    - sphinx
    - sphinx-autodoc-typehints
    - types-pyyaml
    - types-toml
    - vulture
