[default]
check_value = "default"
is_verbose = true
postgres_connection_port = 5432
postgres_container_name = "io_aero_db"
postgres_database_schema = "public"
postgres_dbname = "io_aero_db"
postgres_dbname_admin = "postgres"
postgres_host = "localhost"
postgres_pgdata = "data/postgres"
postgres_user = "io_aero"
postgres_user_admin = "postgres"
postgres_user_guest = "guest"
postgres_version = "16.1"

[dev]

[prod]

[test]
check_value = "test"
postgres_connection_port = 5433
postgres_container_name = "io_aero_db_test"
postgres_password = "postgres_password"
postgres_password_admin = "postgres_password_admin"
postgres_pgdata = "data/postgres_test"
