import argparse

from _typeshed import Incomplete

from iotemplateapp import glob_local as glob_local

ARG_TASK: str
logger: Incomplete

def check_arg_task(args: argparse.Namespace) -> None: ...
def get_args() -> None: ...
def initialise_logger() -> None: ...
def progress_msg(msg: str) -> None: ...
def progress_msg_time_elapsed(duration: int, event: str) -> None: ...
def terminate_fatal(error_msg: str) -> None: ...
def version() -> str: ...
